### ISSUE TITLE
Sporadic event handlers invocation at PMIx_Finalize

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix#190]
@rhc54 this may be a legacy thing but just to make sure. Sometimes in the Jenkins output I see the following message:

```
ERROR [pmix_client.c:52:errhandler]: PMIX client: Error handler with status = -11
```

which comes from the pmix_client.c notification handler:
https://github.com/pmix/master/blob/master/test/pmix_client.c#L52

the corresponding backtrace is following:

```
(gdb) bt
#0  0x00007f439b474dfd in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f439b474c94 in __sleep (seconds=0) at ../sysdeps/unix/sysv/linux/sleep.c:137
#2  0x0000000000401ae1 in errhandler (evhdlr_registration_id=0, status=-11, source=0x7f43940015e0, info=0x7f4394001740, ninfo=1, results=0x0, nresults=0, 
    cbfunc=0x7f439b9acdf7 <progress_local_event_hdlr>, cbdata=0x7f43940015b0) at ../../test/pmix_client.c:55
#3  0x00007f439b9aebc2 in pmix_invoke_local_event_hdlr (chain=0x7f43940015b0) at ../../src/event/pmix_event_notification.c:410
#4  0x00007f439ba45de7 in lost_connection (peer=0x7f439bc861a0 <pmix_client_globals>, err=-11) at ../../src/usock/usock_sendrecv.c:142
#5  0x00007f439ba46e26 in pmix_usock_recv_handler (sd=7, flags=2, cbdata=0x7f439bc861a0 <pmix_client_globals>) at ../../src/usock/usock_sendrecv.c:459
#6  0x00007f439af78a10 in event_persist_closure (ev=<optimized out>, base=0x83f940) at event.c:1319
#7  event_process_active_single_queue (activeq=0x83fd60, base=0x83f940) at event.c:1363
#8  event_process_active (base=<optimized out>) at event.c:1438
#9  event_base_loop (base=0x83f940, flags=1) at event.c:1639
#10 0x00007f439ba48f49 in progress_engine (obj=0x83f898) at ../../src/runtime/pmix_progress_threads.c:149
#11 0x00007f439b781184 in start_thread (arg=0x7f439ab61700) at pthread_create.c:312
#12 0x00007f439b4ae37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) thr 1
[Switching to thread 1 (Thread 0x7f439be84740 (LWP 30692))]
#0  0x00007f439b78265b in pthread_join (threadid=139928335161088, thread_return=0x0) at pthread_join.c:92
92  pthread_join.c: No such file or directory.
(gdb) bt
#0  0x00007f439b78265b in pthread_join (threadid=139928335161088, thread_return=0x0) at pthread_join.c:92
#1  0x00007f439ba48d89 in pmix_thread_join (t=0x83f898, thr_return=0x0) at ../../src/runtime/pmix_progress_threads.c:64
#2  0x00007f439ba48fc2 in stop_progress_engine (trk=0x83f7a0) at ../../src/runtime/pmix_progress_threads.c:164
#3  0x00007f439ba4971f in pmix_progress_thread_finalize (name=0x7f439ba6f350 "PMIX-wide async progress thread") at ../../src/runtime/pmix_progress_threads.c:272
#4  0x00007f439ba47b1a in pmix_rte_finalize () at ../../src/runtime/pmix_finalize.c:105
#5  0x00007f439b9c723a in PMIx_Finalize (info=0x0, ninfo=0) at ../../src/client/pmix_client.c:448
#6  0x00000000004034fa in main (argc=16, argv=0x7ffecc313f38) at ../../test/pmix_client.c:211
```

**Comment by rhc54** [comment]
I suspect the test isn't correctly handling termination and a race condition exists between when the parent and child processes are terminating. This is simply reporting that the process unexpectedly lost connection with the other end, and is probably something to do with the test itself.

**Comment by rhc54** [comment]
This has been fixed by "de-bouncing" the event notification during finalize
