### ISSUE TITLE
Latest PMIx update broken with Open-MPI mpiexec launch

### ISSUE THREAD

**Issue by tonycurtis** [pmix/pmix#761]
Thank you for taking the time to submit an issue!

## Background information

PMIx recently updated to fix PRRTE prun launch problem.  Now MPI-based launch failing.

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

master @ bb797ee7d5bd79d38dc5e49d7ee8950e7e350f93

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: ibv (mlx5)

-----------------------------

## Details of the problem

Latest Open-MPI from git (master @ 2caf1bf0e55973d628b1da9d9714956cff4bcaec) fails as below:

```shell
oshrun: launch: "mpiexec ./a.out"
oshrun: ----------------------------------------------------------------------
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
vsetenv PMIX_SERVER_TMPDIR failed
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[60931,1],2]
  Exit code:    1
--------------------------------------------------------------------------
```

Open-MPI 3.1.0 fails with:

```shell
oshrun: launch: "mpiexec ./a.out"
oshrun: ----------------------------------------------------------------------
[cn002:83773] PMIX ERROR: NOT-SUPPORTED in file ../../../../../pmix-git/src/mca/ptl/tcp/ptl_tcp.c at line 777
*** FATAL: PMIx can't initialize (UNREACHABLE) ***
[cn002:83774] PMIX ERROR: NOT-SUPPORTED in file ../../../../../pmix-git/src/mca/ptl/tcp/ptl_tcp.c at line 777
*** FATAL: PMIx can't initialize (UNREACHABLE) ***
[cn022:146118] PMIX ERROR: NOT-SUPPORTED in file ../../../../../pmix-git/src/mca/ptl/tcp/ptl_tcp.c at line 777
*** FATAL: PMIx can't initialize (UNREACHABLE) ***
[cn022:146117] PMIX ERROR: NOT-SUPPORTED in file ../../../../../pmix-git/src/mca/ptl/tcp/ptl_tcp.c at line 777
*** FATAL: PMIx can't initialize (UNREACHABLE) ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[61028,1],2]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by rhc54** [comment]
I can't replicate this - can you tell me how you configured both OMPI and PMIx?

FWIW: building OMPI against the external PMIx master compiled, but I found a bug that wouldn't allow it to run that way. I'm not sure how you were able to make that configuration work.

**Comment by tonycurtis** [comment]
After further experimentation I think the problem is in interaction between OMPI. and PMIx  I only use OMPI as a PMIx-aware launcher.  It's using the in-tree PMIx.

Using OMPI 3.1.0 as launcher and PMIx 2.1.1 as client in my code, all is well.

With OMPI from git and PMIx 2.1.1, I can run but I get those `vsetenv` messages.

Latest "everything" launches fine with PRRTE.

**Comment by rhc54** [comment]
The update went into the OMPI 3.1 branch, so I am going to close this for now as things should be fixed. Please reopen if otherwise.

**Comment by tonycurtis** [comment]
Will let you know.  thanks.

**Comment by tonycurtis** [comment]
Have just rebuilt both PMIx and PRRTE from git-pull.  Both are using hwloc 2.0.1

prun is core dumping.  Here's a gdb session

```
arcurtis@cn030[1](~/shmem/novo-test) gdb `which prun` core.99538
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /gpfs/home/arcurtis/opt/prrte/git/bin/prun...done.
[New LWP 99538]
[New LWP 99539]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `prun -n 1 ./a.out'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002aaaace90b71 in __strlen_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.1.x86_64 libgcc-4.8.5-4.el7.x86_64 libxml2-2.9.1-6.el7_2.2.x86_64 openssl-libs-1.0.1e-51.el7_2.4.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00002aaaace90b71 in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00002aaaace9087e in strdup () from /lib64/libc.so.6
#2  0x00002aaaae8644b0 in component_open ()
    at ../../../../../pmix-git/src/mca/ptl/tcp/ptl_tcp_component.c:248
#3  0x00002aaaab495bf5 in open_components (
    framework=0x2aaaab6dea00 <pmix_ptl_base_framework>)
    at ../../../../pmix-git/src/mca/base/pmix_mca_base_components_open.c:120
#4  pmix_mca_base_framework_components_open (
    framework=framework@entry=0x2aaaab6dea00 <pmix_ptl_base_framework>,
    flags=flags@entry=PMIX_MCA_BASE_OPEN_DEFAULT)
    at ../../../../pmix-git/src/mca/base/pmix_mca_base_components_open.c:67
#5  0x00002aaaab4b2a0d in pmix_ptl_open (flags=PMIX_MCA_BASE_OPEN_DEFAULT)
    at ../../../../pmix-git/src/mca/ptl/base/ptl_base_frame.c:116
#6  0x00002aaaab49d645 in pmix_mca_base_framework_open (
    framework=0x2aaaab6dea00 <pmix_ptl_base_framework>,
    flags=flags@entry=PMIX_MCA_BASE_OPEN_DEFAULT)
    at ../../../../pmix-git/src/mca/base/pmix_mca_base_framework.c:180
#7  0x00002aaaab478f84 in pmix_rte_init (type=type@entry=4102,
    info=info@entry=0x653b10, ninfo=ninfo@entry=4,
    cbfunc=cbfunc@entry=0x2aaaab47aba0 <pmix_tool_notify_recv>)
    at ../../pmix-git/src/runtime/pmix_init.c:258
#8  0x00002aaaab47b802 in PMIx_tool_init (proc=0x60cd60 <myproc>,
    info=0x653b10, ninfo=4) at ../../pmix-git/src/tool/pmix_tool.c:437
#9  0x0000000000405683 in prun (argc=4, argv=0x7fffffffd158)
    at ../../../../psrvr-git/orte/tools/prun/prun.c:696
#10 0x0000000000402ee0 in main (argc=4, argv=0x7fffffffd158)
    at ../../../../psrvr-git/orte/tools/prun/main.c:13
(gdb)
```

**Comment by rhc54** [comment]
let me poke at it first - probably a trivial change

**Comment by tonycurtis** [comment]
Here's what gdb thinks, might help:
```
gdb -ex=r --args prun -n 1 ./a.out
GNU gdb (GDB) Fedora 8.1-15.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from prun...done.
Starting program: /opt/prrte/bin/prun -n 1 ./a.out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff4ef8700 (LWP 3200)]

Thread 1 "prun" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62		VPCMPEQ (%rdi), %ymm0, %ymm1
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00007ffff6035e3e in __GI___strdup (s=0x0) at strdup.c:41
#2  0x00007ffff3cb529c in component_open () at ../../../../../pmix-git/src/mca/ptl/tcp/ptl_tcp_component.c:248
#3  0x00007ffff7456fbe in open_components (framework=0x7ffff769ca00 <pmix_ptl_base_framework>)
    at ../../../../pmix-git/src/mca/base/pmix_mca_base_components_open.c:120
#4  pmix_mca_base_framework_components_open (framework=framework@entry=0x7ffff769ca00 <pmix_ptl_base_framework>, 
    flags=flags@entry=PMIX_MCA_BASE_OPEN_DEFAULT)
    at ../../../../pmix-git/src/mca/base/pmix_mca_base_components_open.c:67
#5  0x00007ffff7471f9d in pmix_ptl_open (flags=PMIX_MCA_BASE_OPEN_DEFAULT)
    at ../../../../pmix-git/src/mca/ptl/base/ptl_base_frame.c:116
#6  0x00007ffff745df51 in pmix_mca_base_framework_open (framework=0x7ffff769ca00 <pmix_ptl_base_framework>, 
    flags=flags@entry=PMIX_MCA_BASE_OPEN_DEFAULT)
    at ../../../../pmix-git/src/mca/base/pmix_mca_base_framework.c:180
#7  0x00007ffff743c26d in pmix_rte_init (type=type@entry=4102, info=info@entry=0x654970, ninfo=ninfo@entry=4, 
    cbfunc=cbfunc@entry=0x7ffff743dc40 <pmix_tool_notify_recv>) at ../../pmix-git/src/runtime/pmix_init.c:258
#8  0x00007ffff743e74e in PMIx_tool_init (proc=0x60cd80 <myproc>, info=0x654970, ninfo=4)
    at ../../pmix-git/src/tool/pmix_tool.c:437
#9  0x000000000040550c in prun (argc=4, argv=0x7fffffffd6a8) at ../../../../source/orte/tools/prun/prun.c:696
#10 0x0000000000402d36 in main (argc=4, argv=0x7fffffffd6a8) at ../../../../source/orte/tools/prun/main.c:13
(gdb) 
```

**Comment by rhc54** [comment]
yeah, i found the problem - working it now

**Comment by rhc54** [comment]
ok, PR in place - thx! and sorry for the problem

**Comment by tonycurtis** [comment]
looks good +1
